add voice ai classes that access elevenlabs api
aipresenter/aipresenter pull request #38
Opened 2023-06-22 15:33 UTC by ephraimacquah

closes #33

2023-06-22 22:39 UTC, ephraimacquah commented
test_ai_presenter.py needs updated to pass in a voice ai into that instance of aipresenter to pass tests

2023-06-23 13:53 UTC, lpabon requested changes

2023-06-23 13:53 UTC, lpabon commented on ai_presenter/voice_ai/elevenlabs.py
> +        with open(input_file) as file:
Use readlines to read each line of the input file as a json string

2023-06-23 13:53 UTC, lpabon commented on ai_presenter/voice_ai/fake.py
> +            character_config = VoiceConfig(message['speaker'],
Check a `self.characters = {}` to see if created already. If not, then:

```
name = message['speaker']
self.characters[name] = self.new_actor(VoiceConfig(...))
....
self.characters[name].says(...)
```

2023-06-23 15:38 UTC, ephraimacquah commented on ai_presenter/voice_ai/base.py
> +                character_config = VoiceConfig(name,
kept it in this format to keep from going over 80 characters per line

2023-06-24 02:03 UTC, lpabon commented on ai_presenter/voice_ai/elevenlabs.py
> +            data = json.load(file)
Interesting. Let's take a look at the input file on Monday

2023-06-25 23:26 UTC, ephraimacquah commented on ai_presenter/voice_ai/elevenlabs.py
> +            data = json.load(file)
The readlines method of implementation to parse the file fixed this issue

2023-06-26 19:20 UTC, lpabon approved these changes

2023-06-26 19:20 UTC, lpabon commented on ai_presenter/voice_ai/base.py
> +        for message in data['dialogue']:
Check the tab here so that this is in the for loop. It should be under data.

2023-06-27 19:05 UTC, lpabon approved these changes

2023-06-27 19:05 UTC, merged